#!/bin/sh

ghc -fhpc test_OneTeSyntax.hs --make
rm *.tix
./test_OneTeSyntax
hpc report test_OneTeSyntax --exclude=FunctionsAndTypesForParsing --exclude=HelpFunctions
#  --exclude=Main 
hpc markup test_OneTeSyntax --exclude=FunctionsAndTypesForParsing --exclude=HelpFunctions

